"""
NG Beta Regression: Estimate Regional and National Betas from AEO Scenarios
============================================================================

This script is a preprocessing step that runs BEFORE the main aeo_pipeline.py.
It estimates the beta coefficients used in the ReEDS NG supply curve model.

Method
------
The NG supply curve decomposes regional prices as:

    Price(r,t) = Alpha(r,t) + Beta_reg(r) * Q_reg(r,t) + Beta_nat * Q_nat(t)

Alpha varies by region and year (absorbing all time-varying effects).
Beta_reg and Beta_nat are structural parameters estimated via regression.

Estimation uses a joint fixed-effects regression across all regions:

    Price_2004(r,t,s) = Alpha(r,t) + Beta_reg(r) * Q_reg(r,t,s) + Beta_nat * Q_nat(t,s)

Alpha(r,t) is absorbed by demeaning each variable across scenarios within
each (region, year) group. The joint ordinary least squares (OLS) regression
then estimates Beta_nat and all regional Beta_reg values simultaneously.

Data: By default uses ALL available years for selected AEO scenarios
EXCEPT High/Low O&G Supply (held out for alpha computation), but
scenario and year selection can be overridden in config under
scenarios.beta_regression.

Usage
-----
    python aeo_beta_regression.py --config aeo_pipeline_config.json

Outputs
-------
    outputs of beta regression/cd_beta0.csv                  : Regional betas
    outputs of beta regression/national_beta.csv              : National beta
    outputs of beta regression/beta_regression_summary.csv    : Full summary
    outputs of beta regression/alpha_from_beta_regression.csv : Shared alpha(region, year)
    outputs of beta regression/alpha_from_beta_by_scenario.csv : Scenario residual alpha candidates
    outputs of beta regression/alpha from beta regression/alpha_from_beta_shared.csv : Wide shared alpha
    outputs of beta regression/*.png                          : Generated by results_visualization.py
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from aeo_functions import (
    NG_SERIES_NAMES as _SHARED_NG_SERIES_NAMES,
    EiaClient,
    normalize_token,
    resolve_api_key,
    resolve_config_path,
    resolve_region_ids,
    resolve_series_ids,
    setup_logging,
)

# Backwards-compatible alias used throughout this module.
_norm = normalize_token

LOGGER = logging.getLogger("beta_regression")

# ============================================================================
# Constants
# ============================================================================

# Populated at runtime from config["ng"]["cendiv_and_label"] by run().
REGION_TO_LABEL: dict[str, str] = {}

# Beta regression only consumes price + electric-sector demand.
NG_SERIES_NAMES = {
    "price": _SHARED_NG_SERIES_NAMES["price"],
    "demand_elec": _SHARED_NG_SERIES_NAMES["demand_elec"],
}

# ============================================================================
# Helpers
# ============================================================================

def _region_label(region_name: str) -> str:
    """Map an EIA region name (e.g. 'New England') to the ReEDS label
    (e.g. 'New_England'). Raises ValueError if no match is found.
    """
    if region_name in REGION_TO_LABEL:
        return REGION_TO_LABEL[region_name]
    norm = _norm(region_name)
    for name, label in REGION_TO_LABEL.items():
        if _norm(name) == norm or _norm(label) == norm:
            return label
    raise ValueError(f"Unknown region: {region_name}")


def _calc_r2(y: np.ndarray, y_hat: np.ndarray) -> float:
    """R2 for demeaned data (where mean ~= 0, so SS_tot = sum(y^2))."""
    ss_res = float(np.sum((y - y_hat) ** 2))
    ss_tot = float(np.sum(y ** 2))
    return 1 - ss_res / ss_tot if ss_tot > 0 else 0.0


# ============================================================================
# EIA API Client (imported from aeo_functions)
# ============================================================================


# ============================================================================
# Scenario Discovery
# ============================================================================

def discover_regression_scenarios(
    client: EiaClient,
    aeo_year: int,
    include_scenarios: list[str] | None = None,
    exclude_aliases: list[str] | None = None,
) -> list[str]:
    """
    Resolve beta-regression scenarios.

    If include_scenarios is provided, only those scenarios are used
    (matching by scenario id or scenario name, case-insensitive).
    Otherwise, all non-legacy scenarios are used except exclude_aliases.
    """
    facets = client.get_facets(aeo_year, "scenario")
    rows: list[dict[str, str]] = []
    for item in facets:
        sid = str(item.get("id", "")).strip()
        sname = str(item.get("name", "")).strip()
        if not sid or _norm(sid).startswith("aeo"):
            continue
        rows.append({"scenario_id": sid, "scenario_name": sname})

    if include_scenarios:
        selected: list[str] = []
        missing: list[str] = []
        for raw in include_scenarios:
            token = _norm(str(raw).replace("{aeo_year}", str(aeo_year)))
            found = None
            for row in rows:
                sid = str(row["scenario_id"])
                sname = str(row["scenario_name"])
                if _norm(sid) == token or _norm(sname) == token:
                    found = sid
                    break
            if found is None:
                missing.append(str(raw))
                continue
            if found not in selected:
                selected.append(found)
        if missing:
            raise ValueError(
                f"Configured beta_regression.include scenarios not found: {missing}"
            )
        LOGGER.info("Regression scenarios from config (%d): %s", len(selected), selected)
        if exclude_aliases:
            excluded_tokens = {_norm(x) for x in exclude_aliases}
            before = selected[:]
            selected = [
                s for s in selected
                if _norm(s) not in excluded_tokens
                and not any(
                    _norm(r["scenario_name"]) in excluded_tokens
                    for r in rows if str(r["scenario_id"]) == s
                )
            ]
            removed = set(before) - set(selected)
            if removed:
                LOGGER.info("Excluded from include list: %s", sorted(removed))
        if len(selected) < 3:
            LOGGER.warning(
                "Only %d scenarios in beta_regression.include - regression may be unreliable.",
                len(selected),
            )
        return selected

    excluded_tokens = {_norm(x) for x in (exclude_aliases or [])}
    selected: list[str] = []
    excluded: list[str] = []
    for row in rows:
        sid = str(row["scenario_id"])
        sname = str(row["scenario_name"])
        if _norm(sid) in excluded_tokens or _norm(sname) in excluded_tokens:
            excluded.append(f"{sid} ({sname})")
            continue
        selected.append(sid)
    LOGGER.info("Regression scenarios (%d): %s", len(selected), selected)
    if excluded:
        LOGGER.info("Excluded scenarios: %s", excluded)
    if len(selected) < 3:
        LOGGER.warning("Only %d scenarios - regression may be unreliable.",
                       len(selected))
    return selected


# ============================================================================
# Data Fetching
# ============================================================================

def fetch_series(client: EiaClient, aeo_year: int, series_name: str,
                 scenario_ids: list[str], region_ids: list[str],
                 value_col: str,
                 raw_output_path: Path | None = None,
                 start_year: int | None = None,
                 end_year: int | None = None) -> pd.DataFrame:
    """Fetch an AEO series for all scenarios/regions."""
    if (start_year is None) != (end_year is None):
        raise ValueError(
            "Both start_year and end_year must be provided together for fetch_series."
        )
    if start_year is not None and end_year is not None and start_year > end_year:
        raise ValueError(f"Invalid year window: start_year={start_year} > end_year={end_year}")

    series_ids = resolve_series_ids(client, aeo_year, series_name)

    params: list[tuple[str, str]] = [("data[]", "value")]
    if start_year is not None and end_year is not None:
        params.append(("start", str(start_year)))
        params.append(("end", str(end_year)))
    params.extend(("facets[scenario][]", s) for s in scenario_ids)
    params.extend(("facets[regionId][]", r) for r in region_ids)
    params.extend(("facets[seriesId][]", s) for s in series_ids)

    df = client.get_data(aeo_year, params)
    if raw_output_path is not None:
        raw_output_path.parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(raw_output_path, index=False, float_format="%.6f")
        LOGGER.info("Wrote raw data for '%s' to %s (%d rows)",
                    series_name, raw_output_path, len(df))

    df = df.rename(columns={"scenario": "scenario_id"})
    df["region"] = df["regionName"].map(_region_label)
    df["year"] = pd.to_numeric(df["period"], errors="coerce").astype(int)
    df[value_col] = pd.to_numeric(df["value"], errors="coerce")
    df = df.dropna(subset=[value_col])
    df = df[df["scenario_id"].isin(scenario_ids)]

    out = (df.groupby(["scenario_id", "region", "year"], as_index=False)
             [value_col].mean())
    LOGGER.info("Fetched '%s': %d rows (%d scenarios x %d regions x %d years)",
                series_name, len(out), out["scenario_id"].nunique(),
                out["region"].nunique(), out["year"].nunique())
    return out


# ============================================================================
# Joint Beta Regression
# ============================================================================

def estimate_joint_betas(
    price: pd.DataFrame,
    demand: pd.DataFrame,
    deflator: float,
    regions: list[str],
) -> tuple[float, float, dict[str, float], dict[str, dict], pd.DataFrame, float]:
    """
    Estimate all betas jointly from the full equation:

        Price_2004(r,t,s) = Alpha(r,t) + Beta_reg(r)*Q_reg(r,t,s) + Beta_nat*Q_nat(t,s)

    Demeaning across scenarios within each (region, year) removes Alpha.
    Ordinary least squares (OLS) on the demeaned system estimates Beta_nat
    and all Beta_reg simultaneously.

    Returns: (beta_nat, beta_nat_r2, beta_reg_dict, regional_diagnostics,
              regression_data, model_r2)
    """
    # National demand = sum of regional demands per scenario-year
    demand_nat = (demand.groupby(["scenario_id", "year"], as_index=False)
                  ["demand"].sum()
                  .rename(columns={"demand": "demand_nat"}))

    merged = price.merge(demand, on=["scenario_id", "region", "year"])
    merged = merged.merge(demand_nat, on=["scenario_id", "year"])
    merged["price_2004"] = merged["price"] * deflator

    # Demean across scenarios within each (region, year) group
    for col, dcol in [("price_2004", "dp"), ("demand", "dq_reg"),
                      ("demand_nat", "dq_nat")]:
        means = merged.groupby(["year", "region"])[col].transform("mean")
        merged[dcol] = merged[col] - means

    # Build X matrix: [dq_nat, dq_reg(region1), dq_reg(region2), ...]
    region_arr = merged["region"].to_numpy()
    dq_reg_x = merged["dq_reg"].to_numpy()
    x_cols = [merged["dq_nat"].to_numpy()]
    for region in regions:
        x_cols.append(np.where(region_arr == region, dq_reg_x, 0.0))
    X = np.column_stack(x_cols)
    y = merged["dp"].to_numpy()

    # Ordinary least squares
    coeffs = np.linalg.lstsq(X, y, rcond=None)[0]
    beta_nat = float(coeffs[0])
    beta_reg = {region: float(coeffs[i + 1]) for i, region in enumerate(regions)}

    # Diagnostics
    y_hat = X @ coeffs
    model_r2 = _calc_r2(y, y_hat)

    # Partial R2 for national beta (residualize out regional terms)
    merged["dp_hat"] = y_hat
    merged["beta_reg_val"] = merged["region"].map(beta_reg)
    merged["dp_partial_nat"] = (
        merged["dp"] - merged["beta_reg_val"] * merged["dq_reg"]
    )
    beta_nat_r2 = _calc_r2(
        merged["dp_partial_nat"].to_numpy(),
        beta_nat * merged["dq_nat"].to_numpy())

    # Per-region partial R2 (residualize out national term)
    merged["dp_partial_reg"] = merged["dp"] - beta_nat * merged["dq_nat"]
    regional_diag: dict[str, dict] = {}
    for region in regions:
        reg = merged[merged["region"] == region]
        if reg.empty:
            continue
        regional_diag[region] = {
            "r2_partial": _calc_r2(
                reg["dp_partial_reg"].to_numpy(),
                beta_reg[region] * reg["dq_reg"].to_numpy()),
            "r2_full": _calc_r2(
                reg["dp"].to_numpy(), reg["dp_hat"].to_numpy()),
            "n_obs": len(reg),
        }

    # Log results
    LOGGER.info("Joint model: beta_nat=%.10f (partial R2=%.4f, model R2=%.4f)",
                beta_nat, beta_nat_r2, model_r2)
    for region in regions:
        diag = regional_diag.get(region, {})
        LOGGER.info("  %-25s beta=%.10f  (partial R2=%.4f, n=%d)",
                    region, beta_reg[region],
                    diag.get("r2_partial", float("nan")),
                    diag.get("n_obs", 0))

    return beta_nat, beta_nat_r2, beta_reg, regional_diag, merged, model_r2


# ============================================================================
# Output: CSVs
# ============================================================================

def save_outputs(
    out_dir: Path,
    beta_nat: float,
    beta_nat_r2: float,
    beta_reg: dict[str, float],
    regional_diag: dict[str, dict],
    reg_data: pd.DataFrame,
    model_r2: float,
    first_model_year: int,
) -> None:
    """Write beta tables, regression diagnostics, and alpha candidates to CSV."""
    out_dir.mkdir(parents=True, exist_ok=True)

    # cd_beta0.csv
    pd.DataFrame({
        "*cendiv": list(beta_reg.keys()),
        "value": list(beta_reg.values()),
    }).to_csv(out_dir / "cd_beta0.csv", index=False, float_format="%.6f")

    # national_beta.csv
    pd.DataFrame([{
        "beta": beta_nat,
    }]).to_csv(out_dir / "national_beta.csv", index=False, float_format="%.6f")

    # Summary table
    rows = [{
        "scope": "national", "region": "ALL", "beta": beta_nat,
        "r2": beta_nat_r2, "r2_full": model_r2, "n_obs": len(reg_data),
    }]
    for region, beta in beta_reg.items():
        diag = regional_diag.get(region, {})
        rows.append({
            "scope": "regional", "region": region, "beta": beta,
            "r2": diag.get("r2_partial", float("nan")),
            "r2_full": diag.get("r2_full", float("nan")),
            "n_obs": diag.get("n_obs", 0),
        })
    pd.DataFrame(rows).to_csv(
        out_dir / "beta_regression_summary.csv",
        index=False, float_format="%.6f")

    # Regression point data for review
    point_cols = ["scenario_id", "year", "region", "demand", "demand_nat",
                  "price", "price_2004", "dp", "dq_reg", "dq_nat",
                  "dp_partial_reg", "dp_partial_nat", "dp_hat"]
    available = [c for c in point_cols if c in reg_data.columns]
    reg_data[available].to_csv(
        out_dir / "regression_points.csv", index=False, float_format="%.6f")

    # Alpha from beta-step data:
    # 1) Scenario residual alpha candidate:
    #    alpha_candidate(r,t,s) = price_2004 - beta_reg*regional_demand - beta_nat*national_demand
    #    except in the first modeled year, where ReEDS disables both beta terms
    #    and alpha must therefore equal the full converted price.
    # 2) Model alpha indexed by (region, year):
    #    alpha_shared(r,t) = mean_s(alpha_candidate(r,t,s))
    alpha_need = {"scenario_id", "year", "region", "price_2004", "demand", "demand_nat"}
    missing_alpha_cols = sorted(alpha_need - set(reg_data.columns))
    if missing_alpha_cols:
        raise ValueError(
            f"Regression data missing columns needed for alpha export: {missing_alpha_cols}"
        )

    alpha_long = reg_data[
        ["scenario_id", "year", "region", "price_2004", "demand", "demand_nat"]
    ].copy()
    alpha_long = alpha_long.rename(
        columns={"demand": "demand_elec_quads", "demand_nat": "q_nat"}
    )
    alpha_long["beta_reg"] = alpha_long["region"].map(beta_reg)
    if alpha_long["beta_reg"].isna().any():
        bad = sorted(alpha_long.loc[alpha_long["beta_reg"].isna(), "region"].astype(str).unique().tolist())
        raise ValueError(f"Missing regional beta values while exporting alpha: {bad}")
    alpha_long["beta_nat"] = beta_nat
    alpha_long["alpha_candidate"] = (
        alpha_long["price_2004"]
        - alpha_long["beta_reg"] * alpha_long["demand_elec_quads"]
        - alpha_long["beta_nat"] * alpha_long["q_nat"]
    )
    first_year_mask = alpha_long["year"] == first_model_year
    alpha_long.loc[first_year_mask, "alpha_candidate"] = alpha_long.loc[first_year_mask, "price_2004"]
    alpha_long = alpha_long.sort_values(["scenario_id", "year", "region"]).reset_index(drop=True)
    alpha_long.to_csv(
        out_dir / "alpha_from_beta_by_scenario.csv",
        index=False,
        float_format="%.6f",
    )

    alpha_shared = (
        alpha_long.groupby(["region", "year"], as_index=False)["alpha_candidate"]
        .mean()
        .rename(columns={"alpha_candidate": "alpha_2004"})
    )
    n_scenarios = (
        alpha_long.groupby(["region", "year"], as_index=False)["scenario_id"]
        .nunique()
        .rename(columns={"scenario_id": "n_scenarios_used"})
    )
    alpha_shared = alpha_shared.merge(n_scenarios, on=["region", "year"], how="left")
    alpha_shared = alpha_shared.sort_values(["region", "year"]).reset_index(drop=True)
    alpha_shared.to_csv(
        out_dir / "alpha_from_beta_regression.csv",
        index=False,
        float_format="%.6f",
    )

    alpha_wide_dir = out_dir / "alpha from beta regression"
    alpha_wide_dir.mkdir(parents=True, exist_ok=True)
    # Remove stale per-scenario files from earlier output format.
    for old in alpha_wide_dir.glob("alpha_from_beta_*.csv"):
        old.unlink()
    old_index = alpha_wide_dir / "alpha_from_beta_files.csv"
    if old_index.exists():
        old_index.unlink()

    alpha_wide = (
        alpha_shared.pivot_table(
            index="year",
            columns="region",
            values="alpha_2004",
            aggfunc="mean",
        )
        .sort_index()
        .reset_index()
    )
    alpha_wide.to_csv(
        alpha_wide_dir / "alpha_from_beta_shared.csv",
        index=False,
        float_format="%.6f",
    )

    LOGGER.info("Wrote outputs to %s", out_dir)


# ============================================================================
# Pipeline
# ============================================================================

def run(config: dict[str, Any], base_dir: Path) -> None:
    """Main pipeline: discover scenarios, fetch data from EIA API,
    run joint beta regression, and write all outputs.
    """
    ng_cfg = config["ng"]

    # Load shared region mapping from config
    global REGION_TO_LABEL
    REGION_TO_LABEL = ng_cfg["cendiv_and_label"]

    aeo_year = int(config["aeo_year"])
    deflator = float(ng_cfg["price_deflator_to_2004"])
    regions_config = list(ng_cfg["cendiv_and_label"].keys())
    regions = [REGION_TO_LABEL[r] for r in regions_config]

    # API key
    api_key = resolve_api_key(config)
    client = EiaClient(config["api"], api_key)

    scenarios_cfg = config.get("scenarios", {})
    if scenarios_cfg is None:
        scenarios_cfg = {}
    if not isinstance(scenarios_cfg, dict):
        raise ValueError("Config key 'scenarios' must be an object.")
    beta_scen_cfg = scenarios_cfg.get("beta_regression", {})
    if beta_scen_cfg is None:
        beta_scen_cfg = {}
    if not isinstance(beta_scen_cfg, dict):
        raise ValueError("Config key 'scenarios.beta_regression' must be an object.")

    include_cfg = beta_scen_cfg.get("include")
    if include_cfg is not None and not isinstance(include_cfg, list):
        raise ValueError("Config key 'scenarios.beta_regression.include' must be a list.")
    include_scenarios = [str(x).strip() for x in (include_cfg or []) if str(x).strip()]

    exclude_aliases = [str(x).strip() for x in beta_scen_cfg.get("exclude_aliases", [])]

    _sy = beta_scen_cfg.get("start_year")
    _ey = beta_scen_cfg.get("end_year")
    beta_start_year = int(_sy) if _sy is not None else None
    beta_end_year = int(_ey) if _ey is not None else None
    if (beta_start_year is None) != (beta_end_year is None):
        raise ValueError(
            "Config keys 'scenarios.beta_regression.start_year' and "
            "'scenarios.beta_regression.end_year' must be provided together."
        )
    if beta_start_year is not None and beta_end_year is not None and beta_start_year > beta_end_year:
        raise ValueError(
            "Config key 'scenarios.beta_regression': start_year cannot be greater than end_year."
        )
    if beta_start_year is not None and beta_end_year is not None:
        LOGGER.info(
            "Beta regression year range from config: %s-%s",
            beta_start_year, beta_end_year,
        )
    else:
        LOGGER.info("Beta regression year range: all available AEO years.")

    # Step 1: Discover scenarios
    LOGGER.info("Step 1: Discovering AEO %d scenarios...", aeo_year)
    scenario_ids = discover_regression_scenarios(
        client,
        aeo_year,
        include_scenarios=include_scenarios or None,
        exclude_aliases=exclude_aliases or None,
    )

    # Resolve region IDs
    region_ids = list(
        resolve_region_ids(client, aeo_year, regions_config).values()
    )

    # Save raw facets for reference
    out_dir = base_dir / "outputs of beta regression"
    raw_dir = out_dir / "raw_aeo_data"
    raw_dir.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(client.get_facets(aeo_year, "scenario")).to_csv(
        raw_dir / "scenario_facets.csv", index=False)
    pd.DataFrame({"selected_scenario_id": scenario_ids}).to_csv(
        raw_dir / "selected_scenarios.csv", index=False)

    # Step 2: Fetch data
    LOGGER.info("Step 2: Fetching price and demand data...")
    price_raw = fetch_series(
        client, aeo_year, NG_SERIES_NAMES["price"],
        scenario_ids, region_ids, "price",
        raw_output_path=raw_dir / "raw_ng_price.csv",
        start_year=beta_start_year,
        end_year=beta_end_year,
    )
    demand_raw = fetch_series(
        client, aeo_year, NG_SERIES_NAMES["demand_elec"],
        scenario_ids, region_ids, "demand",
        raw_output_path=raw_dir / "raw_ng_demand_elec.csv",
        start_year=beta_start_year,
        end_year=beta_end_year,
    )
    if price_raw.empty or demand_raw.empty:
        raise ValueError(
            "No data available for configured beta regression year range."
        )
    LOGGER.info(
        "Price years used: %s-%s",
        int(price_raw["year"].min()),
        int(price_raw["year"].max()),
    )
    LOGGER.info(
        "Demand years used: %s-%s",
        int(demand_raw["year"].min()),
        int(demand_raw["year"].max()),
    )

    # Step 3: Estimate betas
    LOGGER.info("Step 3: Estimating betas (joint fixed-effects regression)...")
    (beta_nat, beta_nat_r2, beta_reg, regional_diag,
     reg_data, model_r2) = estimate_joint_betas(
        price_raw,
        demand_raw,
        deflator,
        regions,
    )

    # Step 4: Save outputs
    LOGGER.info("Step 4: Saving outputs...")
    save_outputs(out_dir, beta_nat, beta_nat_r2, beta_reg,
                 regional_diag, reg_data, model_r2,
                 first_model_year=int(config["start_year"]))

    # Print summary
    print("\n" + "=" * 60)
    print("RESULTS")
    print("=" * 60)
    print(f"\nNational beta: {beta_nat:.15f}")
    print(f"Model R2:      {model_r2:.6f}")
    print(f"\nRegional betas:")
    for region, beta in beta_reg.items():
        diag = regional_diag.get(region, {})
        print(f"  {region:25s}  {beta:.12f}  "
              f"(partial R2={diag.get('r2_partial', float('nan')):.4f})")
    print(f"\nOutputs: {out_dir}")
    print("\nNext commands:")
    print("  python sync_beta_to_alpha_inputs.py --config aeo_pipeline_config.json")
    print("  python aeo_alpha_regression.py --config aeo_pipeline_config.json")
    print("  python results_visualization.py --config aeo_pipeline_config.json")
    print("=" * 60)


# ============================================================================
# Entry Point
# ============================================================================

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Estimate NG beta coefficients from AEO scenarios")
    parser.add_argument("--config", default="aeo_pipeline_config.json")
    parser.add_argument("--log-level", default="INFO",
                        choices=["DEBUG", "INFO", "WARNING", "ERROR"])
    parser.add_argument("--aeo-year", type=int, default=None)
    args = parser.parse_args()

    setup_logging(args.log_level)

    script_dir = Path(__file__).resolve().parent
    cfg_path = resolve_config_path(args.config, script_dir)

    with cfg_path.open() as f:
        config = json.load(f)
    if args.aeo_year is not None:
        config["aeo_year"] = args.aeo_year

    run(config, script_dir)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:
        LOGGER.exception("Failed: %s", exc)
        sys.exit(1)
